sudo: required

language: python

services:
  - docker

env:
  - IMAGE='php:5.6-cli' TNT_PACKER=pecl
  - IMAGE='php:5.6-cli' TNT_PACKER=pecl_lite
  - IMAGE='php:5.6-cli' TNT_PACKER=pure TNT_CONN_URI=/client/tarantool_client.sock
  - IMAGE='php:5.6-cli' TNT_PACKER=pure COVERAGE_FILE='coverage.clover'
  - IMAGE='php:5.6-cli' TNT_CLIENT=pecl

  - IMAGE='php:7.0-cli' TNT_PACKER=pecl
  - IMAGE='php:7.0-cli' TNT_PACKER=pecl_lite
  - IMAGE='php:7.0-cli' TNT_PACKER=pure

  - IMAGE='php:7.1-cli' TNT_PACKER=pecl
  - IMAGE='php:7.1-cli' TNT_PACKER=pecl_lite
  - IMAGE='php:7.1-cli' TNT_PACKER=pure

  - IMAGE='baptistedonaux/hhvm:3.9' TNT_PACKER=pure
  - IMAGE='baptistedonaux/hhvm:3.12' TNT_PACKER=pure
  - IMAGE='baptistedonaux/hhvm:latest' TNT_PACKER=pure
  - IMAGE='baptistedonaux/hhvm:latest' TNT_PACKER=pure TNT_CONN_URI=/client/tarantool_client.sock

matrix:
  allow_failures:
    - env: IMAGE='php:5.6-cli' TNT_CLIENT=pecl
    - env: IMAGE='baptistedonaux/hhvm:3.9' TNT_PACKER=pure
    - env: IMAGE='baptistedonaux/hhvm:3.12' TNT_PACKER=pure
    - env: IMAGE='baptistedonaux/hhvm:latest' TNT_PACKER=pure
    - env: IMAGE='baptistedonaux/hhvm:latest' TNT_PACKER=pure TNT_CONN_URI=/client/tarantool_client.sock
  fast_finish: true

install:
  - ./dockerfile.py | tee /dev/tty | docker build -t client -

script:
  - docker run -d --name tarantool -v $(pwd):/client -e TNT_LISTEN_URI=$TNT_CONN_URI tarantool/tarantool /client/tests/Integration/client.lua
  - docker run --rm --name client --link tarantool -v $(pwd):/client -w /client client

after_script:
  - if [[ -f "$COVERAGE_FILE" ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      php ocular.phar code-coverage:upload --format=php-clover "$COVERAGE_FILE";
    fi
