sudo: required

language: python

services:
  - docker

env:
  - IMAGE='php:5.4-cli' TNT_PACKER=pecl
  - IMAGE='php:5.4-cli' TNT_PACKER=pecl_lite
  - IMAGE='php:5.4-cli' TNT_PACKER=pure

  - IMAGE='php:5.5-cli' TNT_PACKER=pecl
  - IMAGE='php:5.5-cli' TNT_PACKER=pecl_lite
  - IMAGE='php:5.5-cli' TNT_PACKER=pure

  - IMAGE='php:5.6-cli' TNT_PACKER=pecl
  - IMAGE='php:5.6-cli' TNT_PACKER=pecl_lite
  - IMAGE='php:5.6-cli' TNT_PACKER=pure PHPUNIT_OPTS='--coverage-clover=coverage.clover'
  - IMAGE='php:5.6-cli' TNT_CLIENT=pecl

  - IMAGE='php:7.0-cli' TNT_PACKER=pecl
  - IMAGE='php:7.0-cli' TNT_PACKER=pecl_lite
  - IMAGE='php:7.0-cli' TNT_PACKER=pure

  - IMAGE='baptistedonaux/hhvm:3.9' TNT_PACKER=pure
  - IMAGE='baptistedonaux/hhvm:3.12' TNT_PACKER=pure
  - IMAGE='baptistedonaux/hhvm:latest' TNT_PACKER=pure

matrix:
  allow_failures:
    - env: IMAGE='php:5.6-cli' TNT_CLIENT=pecl
  fast_finish: true

install:
  - ./dockerfile.py | tee /dev/tty | docker build -t client -

script:
  - docker run -d --name tarantool -v $(pwd):/client tarantool/tarantool /client/tests/Integration/instance.lua
  - docker run --rm --name client --link tarantool -v $(pwd):/client -w /client client

after_script:
  - docker run --rm --name client -v $(pwd):/client -w /client client bash -c "
      if [[ -f coverage.clover ]]; then
        curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
        php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
      fi
    "
