name: reusable_qa

on:
  workflow_call:
    inputs:
      artifact_name:
        description: The name of the tarantool build artifact
        default: ubuntu-focal
        required: false
        type: string

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone the tarantool-php/client connector
        uses: actions/checkout@v4
        with:
          repository: tarantool-php/client

      - name: Download the tarantool build artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}

      - name: Install tarantool
        # Now we're lucky: all dependencies are already installed. Check package
        # dependencies when migrating to other OS version.
        run: sudo dpkg -i tarantool*.deb

      - name: Build docker image with connector setup
        run: ./dockerfile.sh | tee /dev/tty | docker build -t client -
        env:
          TNT_LISTEN_URI: localhost:3301

      - name: Run tarantool
        run: tarantool ./tests/Integration/client.lua > tarantool.log 2>&1 &
        env:
          TNT_LISTEN_URI: localhost:3301

      - name: Run connector tests from docker container
        run: >
          docker run --rm --network=host -v /tmp:/tmp -v $PWD:/client -w /client
          -e COMPOSER_ROOT_VERSION=dev-master client
